### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by TOSH702** [sumcoinlabs/sumnode-pi-os#1]
I have installed it line by line and I have now mounted the img again,
from a windows computer this time. I have attached some photos.
![IMG_0366](https://user-images.githubusercontent.com/52512037/62584637-55f9f700-b86a-11e9-9774-0d27609937c4.jpg)
![IMG_0367](https://user-images.githubusercontent.com/52512037/62584638-55f9f700-b86a-11e9-871f-18e0d795056e.jpg)
![IMG_0368](https://user-images.githubusercontent.com/52512037/62584639-55f9f700-b86a-11e9-8bb5-67596bb08fe8.jpg)
![IMG_0369](https://user-images.githubusercontent.com/52512037/62584640-56928d80-b86a-11e9-8cf0-494d56e111d9.jpg)
![IMG_0370](https://user-images.githubusercontent.com/52512037/62584641-56928d80-b86a-11e9-8412-7a91c114d083.jpg)
![IMG_0371](https://user-images.githubusercontent.com/52512037/62584642-56928d80-b86a-11e9-979e-c596a5a6bdf7.jpg)
![IMG_0372](https://user-images.githubusercontent.com/52512037/62584643-56928d80-b86a-11e9-8aa8-cb2fb7f3543f.jpg)
![IMG_0373](https://user-images.githubusercontent.com/52512037/62584644-56928d80-b86a-11e9-9064-050a4449becf.jpg)

**Comment by 5053s** [comment]
Same error - not syncing: VFS: Unable to mount root fs on unknown-block(179,7)

Currently working through https://raspberrypi.stackexchange.com/questions/40854/kernel-panic-not-syncing-vfs-unable-to-mount-root-fs-on-unknown-block179-6

Dr Beco post feels promising 

I've tried changing /dev/mmcblk0p7 to /dev/mmcblk0p6 in conf's without luck too.

**Comment by TOSH702** [comment]
Thank you. I’ve also tried changing it to mmcblk0p6. No success, as you know. I’ll check out the link.

**Comment by sumcoinlabs** [comment]
Identified issue where original IMG was corrupted from Ubuntu backup.   Changes have been made and new configurations were completed - please download from Google Docs link in READ.me and retry.

**Comment by sumcoinlabs** [comment]
@tosh702 please use img in download link from readme for the time being.   

As contributors have time, we can work to shrink this image down for faster use. It it should work now.  

Closing this issue.
