### ISSUE TITLE
I am not showing up on your map?

### ISSUE THREAD

**Issue by TOSH702** [sumcoinlabs/sumnode-pi-os#2]
I have installed the node and it is open on my computer for 4 days now. I do not show up on the map. I have the ports forwarded (I believe I have done this correctly. I attached a pic.) Can you please let me know if I am doing something wrong?
![Screen Shot 2019-08-15 at 12 54 23 PM](https://user-images.githubusercontent.com/52512037/63122687-30e94080-bf5c-11e9-83c5-1a0045383f9b.png)

**Comment by CryptoCloudInc** [comment]
Try removing ipv6 string.   Double check that your LAN ipv4 is correct for the pi as well.

Do you have the rpc, server and daemon information completed inside of .sumcoin?   sumcoin.conf?

**Comment by sumcoinlabs** [comment]
> I have installed the node and it is open on my computer for 4 days now. I do not show up on the map. I have the ports forwarded (I believe I have done this correctly. I attached a pic.) Can you please let me know if I am doing something wrong?
> ![Screen Shot 2019-08-15 at 12 54 23 PM](https://user-images.githubusercontent.com/52512037/63122687-30e94080-bf5c-11e9-83c5-1a0045383f9b.png)

Was this issue resolved?

**Comment by sumcoinlabs** [comment]
Assuming the issue has been resolved after no reply.   Will close now

**Comment by TOSH702** [comment]
I have not had a chance to try it yet. I will this weekend and get back to you. Thank you
